### PR TITLE
[2.20.0] TFS-25362: [DVD] Entered crop parameters are set incorrectly in Crop Panel

### PR DESCRIPTION
**Pull request by dashaezhova**
- [x] [TFS-25362](https://tfs.farheap.com/ONP/davincimarketplace/_workitems/edit/25362): [DVD] Entered crop parameters are set incorrectly in Crop Panel

There is a [reported issue](https://code.google.com/p/jcrop/issues/detail?id=73) on Jcrop official site. There is a [suggested PR](https://github.com/tapmodo/Jcrop/pull/131) to their github repository. But seems like no one is going to fix this issue in the near future.

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by marydruzina** [comment]
:+1:

**Comment by dashaezhova** [comment]
@marydruzina :open_mouth:

**Comment by bozemansoftware** [comment]
:+1:

**Pull request merged**
